# Generated by Django 4.0.5 on 2022-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_likes_value_remove_post_likes_post_likes'),
        ('account', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
