# Generated by Django 4.0.5 on 2022-06-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id']},
        ),
    ]
