# Generated by Django 4.0.5 on 2022-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='website',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
