# Generated by Django 4.0.5 on 2022-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_likes_value_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='value',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
