# Generated by Django 4.0.5 on 2022-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=250),
        ),
    ]
