# Generated by Django 4.0.2 on 2022-06-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_story_storystream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='caption',
        ),
    ]
