# Generated by Django 4.0.5 on 2022-07-02 17:01

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=post.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Tag'),
        ),
    ]
