# Generated by Django 4.0.5 on 2022-07-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_like_remove_post_likes_post_likes_delete_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(blank=True, null=True, related_name='contents', to='post.postfilecontent'),
        ),
    ]
